# requiring the environment of Ruby 2.3.x
image: ruby:2.6.5

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
   - bundle install
# the 'pages' job will deploy and build your site to the 'public' path
pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
    - bundle exec jekyll build -d public/
  artifacts:
     paths:
       - public
  only:
   - master # this job will affect only the 'master' branch
