# requiring the environment of Ruby 2.6.x
image: ruby:2.6.5

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/ruby

before_script:
  - bundle install -j $(nproc) --path vendor  # Install dependencies into ./vendor/ruby
  
# the 'pages' job will deploy and build your site to the 'public' path
pages:
  stage: deploy
  script:
    - bundle exec jekyll build -d public
  artifacts:
     paths:
       - public
  only:
   - master # this job will affect only the 'master' branch
